FROM python:2.7

# Get docker config
ENV DOCKER_CONFIG=/tmp/

# Install packages required for the tests
COPY test-requirements.txt /tmp/test-requirements.txt
RUN pip install --no-cache-dir -r /tmp/test-requirements.txt

# Install the package requirements
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
