FROM rackattack-nas.dc1:5000/dev-base:68edfd0d862e1a24764daea9d2c55eb360190ad5

# Upgrade docker client version
RUN curl https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz | tar xz -C /tmp/ && \
    chmod +x /tmp/docker && mv -f /tmp/docker/* /usr/local/bin/

COPY test-requirements.txt /tmp/test-requirements.txt
RUN pip install --no-cache-dir -r /tmp/test-requirements.txt

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
